# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='country',
            field=models.CharField(default='USA', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='street_address1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='street_address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
