# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170209_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='state',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='street_address1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='street_address2',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
