# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170226_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
