# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170228_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
