# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170312_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('despcrition', models.TextField()),
            ],
        ),
    ]
