# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='despcrition',
            field=models.TextField(max_length=2000),
        ),
    ]
